import { useMemo, useState } from 'react'
import { AlertTriangle, CalendarDays, ChevronLeft, ChevronRight, CloudSun, Grape, LayoutDashboard, Menu, Search, Settings, Sprout, Target, Truck, X } from 'lucide-react'
import './styles.css'
import { ForecastingPage } from '../engineer3'

type Approval = 'Not Required' | 'Awaiting Approval' | 'Approved' | 'Hold'
type Block = { id:string; vineyard:string; block:string; client:string; variety:string; acres:number; tons:number; actualTons?:number; brix:number; targetBrix:number; start:string; end:string; confidence:number; approval:Approval }
type Assignment = { blockId:string; date:string }
const START='2026-09-14'
const blocks:Block[]=[
 {id:'robles',vineyard:'Los Robles',block:'D-17',client:'Winery A',variety:'Merlot',acres:18,tons:120,actualTons:134,brix:24.2,targetBrix:24,start:'2026-09-14',end:'2026-09-15',confidence:91,approval:'Approved'},
 {id:'smith12',vineyard:'Smith',block:'B-12',client:'Winery A',variety:'Cabernet',acres:42,tons:100,brix:23.5,targetBrix:24,start:'2026-09-15',end:'2026-09-17',confidence:88,approval:'Approved'},
 {id:'jones',vineyard:'Jones Ranch',block:'B-4',client:'Winery B',variety:'Chardonnay',acres:24,tons:60,brix:22.7,targetBrix:23,start:'2026-09-15',end:'2026-09-17',confidence:86,approval:'Not Required'},
 {id:'mesa',vineyard:'Mesa Ridge',block:'B-7',client:'Oak & Stone',variety:'Pinot Noir',acres:31,tons:200,brix:22.1,targetBrix:23,start:'2026-09-16',end:'2026-09-18',confidence:76,approval:'Awaiting Approval'},
 {id:'stone',vineyard:'Stone Creek',block:'A-03',client:'Cedar Cellars',variety:'Sauvignon Blanc',acres:27,tons:100,brix:23.0,targetBrix:23,start:'2026-09-17',end:'2026-09-19',confidence:79,approval:'Approved'},
 {id:'smith14',vineyard:'Smith',block:'B-14',client:'Winery A',variety:'Cabernet',acres:20,tons:80,brix:23.1,targetBrix:24,start:'2026-09-16',end:'2026-09-17',confidence:87,approval:'Approved'},
 {id:'coyote',vineyard:'Coyote Run',block:'B-08',client:'Winery C',variety:'Zinfandel',acres:20,tons:76,brix:22.4,targetBrix:24,start:'2026-09-18',end:'2026-09-20',confidence:61,approval:'Hold'},
 {id:'river',vineyard:'River Bend',block:'7',client:'Oak & Stone',variety:'Cabernet Franc',acres:25,tons:96,brix:22.8,targetBrix:24,start:'2026-09-20',end:'2026-09-22',confidence:68,approval:'Awaiting Approval'},
]
const seeded:Assignment[]=[{blockId:'robles',date:'2026-09-14'},{blockId:'smith12',date:'2026-09-15'},{blockId:'jones',date:'2026-09-15'},{blockId:'mesa',date:'2026-09-16'},{blockId:'stone',date:'2026-09-17'}]
const seedCapacity:Record<string,number>={'2026-09-14':7,'2026-09-15':8,'2026-09-16':8,'2026-09-17':8,'2026-09-18':7,'2026-09-19':4,'2026-09-20':4}
const asDate=(v:string)=>new Date(v+'T12:00:00')
const iso=(d:Date)=>d.toISOString().slice(0,10)
const add=(v:string,n:number)=>{const d=asDate(v);d.setDate(d.getDate()+n);return iso(d)}
const short=(v:string)=>asDate(v).toLocaleDateString('en-US',{month:'short',day:'numeric'})
const dayDiff=(a:string,b:string)=>Math.round((asDate(a).getTime()-asDate(b).getTime())/86400000)
const timing=(day:string,b:Block)=>day<b.start?{state:'early',days:dayDiff(b.start,day)}:day>b.end?{state:'late',days:dayDiff(day,b.end)}:{state:'window',days:0}
const loads=(tons:number,tonsPerLoad:number)=>Math.ceil(tons/tonsPerLoad)

function BlockCard({block,day,days,tonsPerLoad,move}:{block:Block;day:string;days:string[];tonsPerLoad:number;move:(blockId:string,date:string)=>void}){
 const t=timing(day,block), variance=block.actualTons?Math.round((block.actualTons-block.tons)/block.tons*100):null
 return <article className={`block-card timing-${t.state}`} draggable onDragStart={e=>e.dataTransfer.setData('block',block.id)}>
  <div className="block-title"><div><b>{block.vineyard} · {block.block}</b><span>{block.variety} · {block.client}</span></div><i>⠿</i></div>
  <div className="numbers"><span><b>{block.acres}</b> acres</span><span><b>{block.tons}</b> tons</span><span><b>{loads(block.tons,tonsPerLoad)}</b> loads</span></div>
  <div className="brix"><span>Brix <b>{block.brix}</b> → target {block.targetBrix}</span><span className={`approval ${block.approval.toLowerCase().replaceAll(' ','-')}`}>{block.approval}</span></div>
  <p className="forecast"><CloudSun/>Forecast {short(block.start)}–{short(block.end).replace(/^\w+\s/,'')} · {block.confidence}%</p>
  {block.confidence<70&&<p className="low-confidence">Low confidence · forecast is an estimate</p>}
  <div className={`timing timing-${t.state}`}>{t.state==='window'?'On window':`${t.days} day${t.days===1?'':'s'} ${t.state}`}<small>Scheduled {short(day)}</small></div>
  {variance!==null&&<div className="actual">Actual {block.actualTons} tons <b>+{variance}% vs estimate</b></div>}
  <label>Move <select value={day} onChange={e=>move(block.id,e.target.value)}>{days.map(d=><option key={d} value={d}>{asDate(d).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</option>)}<option value="">Unscheduled</option></select></label>
 </article>
}

export default function App(){
 const [week,setWeek]=useState(START),[assignments,setAssignments]=useState(seeded),[capacity,setCapacity]=useState(seedCapacity),[tonsPerLoad,setTonsPerLoad]=useState(20),[query,setQuery]=useState(''),[mobile,setMobile]=useState(false),[toast,setToast]=useState(''),[workspace,setWorkspace]=useState<'Harvest Planner'|'Forecasting'>('Harvest Planner')
 const days=useMemo(()=>Array.from({length:7},(_,i)=>add(week,i)),[week]), assigned=new Set(assignments.map(a=>a.blockId))
 const readySoon=blocks.filter(b=>!assigned.has(b.id)&&b.start<=add(week,7)).sort((a,b)=>a.end.localeCompare(b.end)||a.start.localeCompare(b.start))
 const unscheduled=readySoon.filter(b=>`${b.vineyard} ${b.block} ${b.variety} ${b.client}`.toLowerCase().includes(query.toLowerCase()))
 const move=(id:string,d:string)=>{setAssignments(a=>d?[...a.filter(x=>x.blockId!==id),{blockId:id,date:d}]:a.filter(x=>x.blockId!==id));setToast(d?`${blocks.find(b=>b.id===id)?.vineyard} ${blocks.find(b=>b.id===id)?.block} scheduled ${short(d)}`:'Block returned to Ready Soon');setTimeout(()=>setToast(''),2000)}
 const scheduled=assignments.filter(a=>days.includes(a.date)).map(a=>blocks.find(b=>b.id===a.blockId)!).filter(Boolean)
 const tons=scheduled.reduce((n,b)=>n+b.tons,0), required=scheduled.reduce((n,b)=>n+loads(b.tons,tonsPerLoad),0), trucks=days.reduce((n,d)=>n+(capacity[d]||0),0), gap=Math.max(0,required-trucks)
 const outsideCount=assignments.filter(a=>days.includes(a.date)).filter(a=>timing(a.date,blocks.find(b=>b.id===a.blockId)!).state!=='window').length
 return <div className="shell" onClickCapture={event=>{const label=(event.target as HTMLElement).closest('button')?.textContent;if(label?.includes('Forecasting'))setWorkspace('Forecasting');if(label?.includes('Harvest Planner'))setWorkspace('Harvest Planner')}}>
  <aside className={mobile?'open':''}><div className="brand"><span><Sprout/></span><div><b>VineFlow</b><small>HARVEST OPERATIONS</small></div></div><button className="close" onClick={()=>setMobile(false)}><X/></button><nav>{[['Overview',LayoutDashboard],['Block Status',Grape],['Harvest Planner',CalendarDays],['Forecasting',CloudSun],['Fleet & Logistics',Truck]].map(([n,I]:any)=><button className={n==='Harvest Planner'?'active':''} key={n} onClick={()=>{if(n==='Overview'||n==='Block Status')window.location.hash='overview';if(n==='Harvest Planner')window.location.hash='planner'}}><I size={18}/>{n}</button>)}</nav><div className="bottom"><button><Settings size={18}/>Settings</button><div className="profile"><span>JM</span><div><b>Jordan Miller</b><small>Operations Manager</small></div></div></div></aside>
  <main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vineyards, blocks, varieties..."/></div><span>2026 Harvest</span></header>
  <div className="content">{workspace==='Forecasting'?<ForecastingPage/>:<><div className="page-head"><div><p>HARVEST PLANNER</p><h1>Harvest week · {short(week)}–{short(add(week,6)).replace(/^\w+\s/,'')}</h1><span>What is coming ready, where is it scheduled, and do we have enough trucks?</span></div><div className="week-nav"><button onClick={()=>setWeek(add(week,-7))}><ChevronLeft/></button><b><CalendarDays/>Week of {short(week)}</b><button onClick={()=>setWeek(add(week,7))}><ChevronRight/></button></div></div>
  <section className="metrics hero-metrics"><div><span>Expected harvest</span><b>{tons} <i>tons</i></b><small>{scheduled.length} scheduled blocks</small></div><div><span>Expected loads</span><b>{required}</b><small>1 load = 1 truck</small></div><div><span>Trucks scheduled</span><b>{trucks}</b><small>across seven nights</small></div><div className={gap?'gap':''}><span>Capacity gap</span><b>{gap} <i>loads</i></b><small>{gap?`Add ${gap} trucks across the week`:'Weekly capacity covered'}</small></div><div><span>Ready soon</span><b>{readySoon.length}</b><small>not yet scheduled</small></div><div><span>Outside window</span><b>{outsideCount}</b><small>scheduled blocks</small></div></section>
  <section className="ready-soon"><div className="section-head"><div><h2><Target/>Ready soon · not scheduled</h2><p>Sorted by forecast urgency. Predicted readiness does not equal winery approval.</p></div><span>{readySoon.length} BLOCKS</span></div><div className="ready-grid">{unscheduled.map(b=><article key={b.id} draggable onDragStart={e=>e.dataTransfer.setData('block',b.id)}><div className="urgency"><b>{b.end<week?'Past window':b.start<=week?'Inside window':'Coming ready'}</b><span>{b.approval}</span></div><h3>{b.vineyard} · {b.block}</h3><p>{b.variety} · {b.client}</p><div className="ready-data"><span><small>BRIX</small>{b.brix} → {b.targetBrix}</span><span><small>FORECAST</small>{short(b.start)}–{short(b.end).replace(/^\w+\s/,'')}</span><span><small>VOLUME</small>{b.tons} t · {loads(b.tons,tonsPerLoad)} loads</span></div><div className="confidence">{b.confidence}% confidence {b.confidence<70&&<b>LOW</b>}</div><select defaultValue="" onChange={e=>move(b.id,e.target.value)}><option value="" disabled>Add to schedule…</option>{days.map(d=><option key={d} value={d}>{asDate(d).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}</option>)}</select></article>)}</div></section>
  <div className="planner-toolbar"><div><h2>Nightly plan</h2><span>Drag blocks between nights to rebalance capacity.</span></div><label>Default tons per load <input type="number" min="1" value={tonsPerLoad} onChange={e=>setTonsPerLoad(Math.max(1,+e.target.value||1))}/><b>tons / load</b></label></div>
  <section className="board">{days.map(d=>{const bs=assignments.filter(a=>a.date===d).map(a=>blocks.find(b=>b.id===a.blockId)!).filter(Boolean), expected=bs.reduce((n,b)=>n+b.tons,0), actual=bs.reduce((n,b)=>n+(b.actualTons||0),0), dayLoads=bs.reduce((n,b)=>n+loads(b.tons,tonsPerLoad),0), available=capacity[d]||0, delta=available-dayLoads, utilization=available?dayLoads/available:dayLoads?2:0, risk=delta<0?'red':utilization>=.9?'yellow':'green', surplusDay=days.find(x=>x!==d&&((capacity[x]||0)-assignments.filter(a=>a.date===x).map(a=>blocks.find(b=>b.id===a.blockId)!).filter(Boolean).reduce((n,b)=>n+loads(b.tons,tonsPerLoad),0))>0);return <div className={`day risk-${risk}`} key={d} onDragOver={e=>e.preventDefault()} onDrop={e=>move(e.dataTransfer.getData('block'),d)}><div className="summary"><div className="day-title"><div><b>{asDate(d).toLocaleDateString('en-US',{weekday:'long'})}</b><span>{short(d)}</span></div><strong className={risk}>{risk==='red'?'Truck deficit':risk==='yellow'?'Near capacity':'Capacity sufficient'}</strong></div><div className="stats"><span><b>{bs.length}</b> blocks</span><span><b>{expected}</b> tons</span><span><b>{dayLoads}</b> loads</span></div>{actual>0&&<div className="daily-actual">Actual <b>{actual} tons</b> · +{actual-expected} tons · +{loads(actual,tonsPerLoad)-dayLoads} loads</div>}<div className="trucks"><label><Truck/>Trucks scheduled</label><div><button onClick={()=>setCapacity(c=>({...c,[d]:Math.max(0,available-1)}))}>−</button><input type="number" min="0" value={available} onChange={e=>setCapacity(c=>({...c,[d]:Math.max(0,+e.target.value||0)}))}/><button onClick={()=>setCapacity(c=>({...c,[d]:available+1}))}>+</button></div></div><div className="math">{expected} tons ÷ {tonsPerLoad} tons/load = <b>{dayLoads} loads</b></div><div className={`recommendation ${risk}`}>{delta<0?<><AlertTriangle/><span><b>Add {Math.abs(delta)} trucks {asDate(d).toLocaleDateString('en-US',{weekday:'long'})}.</b>{surplusDay&&` Possible alternative: move loads to ${asDate(surplusDay).toLocaleDateString('en-US',{weekday:'long'})}.`}</span></>:delta===0?<><Target/><span><b>At capacity.</b> No buffer for estimate variance.</span></>:<><Truck/><span><b>{delta} trucks available.</b> Capacity buffer for this night.</span></>}</div></div><div className="cards">{bs.length?bs.map(b=><BlockCard key={b.id} block={b} day={d} days={days} tonsPerLoad={tonsPerLoad} move={move}/>):<div className="empty"><CalendarDays/>Drop a ready block here to schedule</div>}</div></div>})}</section>
  <section className="season-status"><div><span>Season status · from the Bible</span><b>4,820 acres picked</b></div><div><span>Harvest remaining</span><b>2,180 acres</b></div><div><span>Expected loads remaining</span><b>312 loads</b></div><small>Mock status until Engineer 1 integration is connected</small></section>
  </>}</div></main>{toast&&<div className="toast">{toast}</div>}
 </div>
}
