import { useMemo, useState } from 'react'
import { AlertTriangle, CalendarDays, ChevronLeft, ChevronRight, CloudSun, Grape, Layers3, LayoutDashboard, Menu, Search, Settings, Sprout, Target, Truck, X } from 'lucide-react'
import './styles.css'
import { liveAssignments, liveBlocks, livePlannerMeta, type PlannerAssignment as Assignment, type PlannerBlock as Block } from './engineer1Data'
import { ForecastingPage } from '../engineer3'

const START=livePlannerMeta.asOfDate
const blocks=liveBlocks
const seeded:Assignment[]=liveAssignments
const seedCapacity:Record<string,number>={}
const asDate=(v:string)=>new Date(v+'T12:00:00')
const iso=(d:Date)=>d.toISOString().slice(0,10)
const add=(v:string,n:number)=>{const d=asDate(v);d.setDate(d.getDate()+n);return iso(d)}
const short=(v:string)=>asDate(v).toLocaleDateString('en-US',{month:'short',day:'numeric'})
const dayDiff=(a:string,b:string)=>Math.round((asDate(a).getTime()-asDate(b).getTime())/86400000)
const timing=(day:string,b:Block)=>!b.start||!b.end?{state:'unknown',days:0}:day<b.start?{state:'early',days:dayDiff(b.start,day)}:day>b.end?{state:'late',days:dayDiff(day,b.end)}:{state:'window',days:0}
const loads=(tons:number,tonsPerLoad:number)=>Math.ceil(tons/tonsPerLoad)
const truckNotice=(day:string)=>{
 const harvest=new Date(`${day}T18:00:00`), hours=(harvest.getTime()-Date.now())/3600000
 if(hours<0)return {level:'red',label:'Harvest time passed',message:'Confirm coverage immediately.'}
 if(hours<12)return {level:'red',label:'Inside 12-hour minimum',message:'Urgent: call the truck provider now.'}
 if(hours<24)return {level:'yellow',label:'Inside 24-hour preferred window',message:'Order now; minimum notice is still met.'}
 const deadline=new Date(harvest.getTime()-24*3600000).toLocaleString('en-US',{weekday:'short',hour:'numeric',minute:'2-digit'})
 return {level:'green',label:'Notice window open',message:`Order by ${deadline} for preferred notice.`}
}

function BlockCard({block,day,days,tonsPerLoad,scheduledLoads,appointment,confirmed,move}:{block:Block;day:string;days:string[];tonsPerLoad:number;scheduledLoads:number|null;appointment:string|null;confirmed:boolean;move:(blockId:string,date:string)=>void}){
 const t=timing(day,block), variance=block.actualTons?Math.round((block.actualTons-block.tons)/block.tons*100):null
 return <article className={`block-card timing-${t.state}`} draggable onDragStart={e=>e.dataTransfer.setData('block',block.id)}>
  <div className="block-title"><div><b>{block.vineyard} · {block.block}</b><span>{block.variety} · {block.client}</span></div><i>⠿</i></div>
  <div className="numbers"><span><b>{block.acres.toFixed(1)}</b> acres left</span><span><b>{block.tons.toFixed(1)}</b> ton cross-check</span><span><b>{scheduledLoads??loads(block.tons,tonsPerLoad)}</b> explicit loads</span></div>
  <div className="brix"><span>{block.brix!==null?<>Brix <b>{block.brix}</b>{block.targetBrix!==null&&<> → target {block.targetBrix}</>}</>:'Brix not available'}</span><span className={`approval ${confirmed?'approved':'awaiting-approval'}`}>{confirmed?'Schedule confirmed':'Schedule unconfirmed'}</span></div>
  <p className="forecast"><CloudSun/>{block.start&&block.end?<>Readiness signal {short(block.start)}–{short(block.end).replace(/^\w+\s/,'')}{block.confidence!==null&&` · ${block.confidence}%`}</>:'Forecast not available'}</p>
  {block.confidence!==null&&block.confidence<70&&<p className="low-confidence">Low confidence · forecast is an estimate</p>}
  <div className={`timing timing-${t.state}`}>{t.state==='window'?'On window':t.state==='unknown'?'Forecast pending':`${t.days} day${t.days===1?'':'s'} ${t.state}`}<small>Scheduled {short(day)}</small></div>
  <div className="actual">Delivery appointment <b>{appointment||'Not listed'}</b></div>
  {variance!==null&&<div className="actual">Actual {block.actualTons} tons <b>+{variance}% vs estimate</b></div>}
  <label>Move <select value={day} onChange={e=>move(block.id,e.target.value)}>{days.map(d=><option key={d} value={d}>{asDate(d).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</option>)}<option value="">Unscheduled</option></select></label>
 </article>
}

export default function App(){
 const [week,setWeek]=useState(START),[assignments,setAssignments]=useState(seeded),[capacity,setCapacity]=useState(seedCapacity),[tonsPerLoad,setTonsPerLoad]=useState(23.5),[query,setQuery]=useState(''),[mobile,setMobile]=useState(false),[toast,setToast]=useState('')
 const [workspace,setWorkspace]=useState<'Harvest Planner'|'Forecasting'>(window.location.hash==='#forecasting'?'Forecasting':'Harvest Planner')
 const days=useMemo(()=>Array.from({length:7},(_,i)=>add(week,i)),[week]), assigned=new Set(assignments.map(a=>a.blockId))
 const readySoon=blocks.filter(b=>!assigned.has(b.id)&&((b.start!==null&&b.start<=add(week,7))||(b.brix!==null&&b.brix>=23))).sort((a,b)=>(a.end||'9999').localeCompare(b.end||'9999')||(b.brix||0)-(a.brix||0))
 const unscheduled=readySoon.filter(b=>`${b.vineyard} ${b.block} ${b.variety} ${b.client}`.toLowerCase().includes(query.toLowerCase()))
 const move=(id:string,d:string)=>{setAssignments(a=>d?[...a.filter(x=>x.blockId!==id),{blockId:id,date:d,scheduledLoads:null,appointment:null,confirmed:false}]:a.filter(x=>x.blockId!==id));setToast(d?`${blocks.find(b=>b.id===id)?.vineyard} ${blocks.find(b=>b.id===id)?.block} scheduled ${short(d)}`:'Block returned to Ready Soon');setTimeout(()=>setToast(''),2000)}
 const scheduled=assignments.filter(a=>days.includes(a.date)).map(a=>blocks.find(b=>b.id===a.blockId)!).filter(Boolean)
 const tons=scheduled.reduce((n,b)=>n+b.tons,0), required=assignments.filter(a=>days.includes(a.date)).reduce((n,a)=>n+(a.scheduledLoads??loads(blocks.find(b=>b.id===a.blockId)?.tons||0,tonsPerLoad)),0), trucks=days.reduce((n,d)=>n+(capacity[d]||0),0), gap=Math.max(0,required-trucks)
 const outsideCount=assignments.filter(a=>days.includes(a.date)).filter(a=>{const b=blocks.find(b=>b.id===a.blockId);return b&&timing(a.date,b).state!=='window'&&timing(a.date,b).state!=='unknown'}).length
 return <div className="shell">
  <aside className={mobile?'open':''}><div className="brand"><span><Sprout/></span><div><b>VineFlow</b><small>HARVEST OPERATIONS</small></div></div><button className="close" onClick={()=>setMobile(false)}><X/></button><nav>{[['Overview',LayoutDashboard,'overview'],['Block Status',Grape,'blocks'],['Harvest Planner',CalendarDays,'planner'],['Forecasting',CloudSun,'forecasting'],['Fleet & Logistics',Truck,'planner'],['Satellite Intelligence',Layers3,'satellite']].map(([n,I,route]:any)=><button className={n===workspace?'active':''} key={n} onClick={()=>{window.location.hash=route;if(route==='planner')setWorkspace('Harvest Planner');if(route==='forecasting')setWorkspace('Forecasting')}}><I size={18}/>{n}</button>)}</nav><div className="bottom"><button><Settings size={18}/>Settings</button><div className="profile"><span>JM</span><div><b>Jordan Miller</b><small>Operations Manager</small></div></div></div></aside>
  <main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vineyards, blocks, varieties..."/></div><span>2026 Harvest</span></header>
  <div className="content">{workspace==='Forecasting'?<ForecastingPage/>:<><div className="page-head"><div><p>HARVEST PLANNER</p><h1>Harvest week · {short(week)}–{short(add(week,6)).replace(/^\w+\s/,'')}</h1><span>What is coming ready, where is it scheduled, and do we have enough trucks?</span></div><div className="week-nav"><button onClick={()=>setWeek(add(week,-7))}><ChevronLeft/></button><b><CalendarDays/>Week of {short(week)}</b><button onClick={()=>setWeek(add(week,7))}><ChevronRight/></button></div></div>
  <section className="metrics hero-metrics"><div><span>Expected harvest</span><b>{tons.toFixed(1)} <i>tons</i></b><small>{scheduled.length} scheduled blocks</small></div><div><span>Expected loads</span><b>{required}</b><small>1 load = 1 truck</small></div><div><span>Trucks ordered</span><b>{trucks}</b><small>enter confirmed orders below</small></div><div className={gap?'gap':''}><span>Still to order</span><b>{gap} <i>trucks</i></b><small>{gap?'Unlimited supply assumed · notice required':'All required trucks ordered'}</small></div><div><span>Ready soon</span><b>{readySoon.length}</b><small>not yet scheduled</small></div><div><span>Outside window</span><b>{outsideCount}</b><small>scheduled blocks</small></div></section>
  <section className="ready-soon"><div className="section-head"><div><h2><Target/>Ready soon · not scheduled</h2><p>Forecast windows when available; otherwise a Brix-based status watch from the latest spreadsheet. Winery approval remains separate.</p></div><span>{readySoon.length} BLOCKS</span></div><div className="ready-grid">{unscheduled.map(b=><article key={b.id} draggable onDragStart={e=>e.dataTransfer.setData('block',b.id)}><div className="urgency"><b>{b.end&&b.end<week?'Past window':b.start&&b.start<=week?'Inside window':b.start?'Coming ready':'Brix status watch'}</b><span>{b.approval}</span></div><h3>{b.vineyard} · {b.block}</h3><p>{b.variety} · {b.client}</p><div className="ready-data"><span><small>BRIX</small>{b.brix??'—'}</span><span><small>READINESS</small>{b.start&&b.end?`${short(b.start)}–${short(b.end).replace(/^\w+\s/,'')}`:'Forecast pending'}</span><span><small>VOLUME</small>{b.tons.toFixed(1)} t · {loads(b.tons,tonsPerLoad)} loads</span></div><div className="confidence">{b.confidence!==null?`${b.confidence}% confidence`:'Forecast confidence not available'} {b.confidence!==null&&b.confidence<70&&<b>LOW</b>}</div><select defaultValue="" onChange={e=>move(b.id,e.target.value)}><option value="" disabled>Add to schedule…</option>{days.map(d=><option key={d} value={d}>{asDate(d).toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}</option>)}</select></article>)}</div></section>
  <div className="planner-toolbar"><div><h2>Nightly plan</h2><span>Drag blocks between nights to rebalance capacity.</span></div><label>Default tons per load <input type="number" min="1" step="0.5" value={tonsPerLoad} onChange={e=>setTonsPerLoad(Math.max(1,+e.target.value||1))}/><b>tons / load</b></label></div>
  <section className="board">{days.map(d=>{const dayAssignments=assignments.filter(a=>a.date===d), bs=dayAssignments.map(a=>blocks.find(b=>b.id===a.blockId)!).filter(Boolean), expected=bs.reduce((n,b)=>n+b.tons,0), actual=bs.reduce((n,b)=>n+(b.actualTons||0),0), dayLoads=dayAssignments.reduce((n,a)=>n+(a.scheduledLoads??loads(blocks.find(b=>b.id===a.blockId)?.tons||0,tonsPerLoad)),0), ordered=capacity[d]||0, delta=ordered-dayLoads, utilization=ordered?dayLoads/ordered:dayLoads?2:0, risk=delta<0?'red':utilization>=.9?'yellow':'green', notice=truckNotice(d);return <div className={`day risk-${risk}`} key={d} onDragOver={e=>e.preventDefault()} onDrop={e=>move(e.dataTransfer.getData('block'),d)}><div className="summary"><div className="day-title"><div><b>{asDate(d).toLocaleDateString('en-US',{weekday:'long'})}</b><span>{short(d)}</span></div><strong className={risk}>{delta<0?`${Math.abs(delta)} to order`:risk==='yellow'?'Fully allocated':'Orders covered'}</strong></div><div className="stats"><span><b>{bs.length}</b> blocks</span><span><b>{expected.toFixed(1)}</b> ton cross-check</span><span><b>{dayLoads}</b> explicit loads</span></div>{actual>0&&<div className="daily-actual">Actual <b>{actual} tons</b> · {actual-expected>=0?'+':''}{actual-expected} tons</div>}<div className="trucks"><label><Truck/>Trucks already ordered</label><div><button onClick={()=>setCapacity(c=>({...c,[d]:Math.max(0,ordered-1)}))}>−</button><input type="number" min="0" value={ordered} onChange={e=>setCapacity(c=>({...c,[d]:Math.max(0,+e.target.value||0)}))}/><button onClick={()=>setCapacity(c=>({...c,[d]:ordered+1}))}>+</button></div></div><div className="math">Explicit schedule: <b>{dayLoads} loads = {dayLoads} trucks</b> · {expected.toFixed(1)} tons cross-check at {tonsPerLoad} t/load</div><div className={`notice ${notice.level}`}><b>{notice.label}</b><span>{notice.message}</span></div><div className={`recommendation ${delta<0?notice.level:risk}`}>{delta<0?<><AlertTriangle/><span><b>Order {Math.abs(delta)} more trucks for {asDate(d).toLocaleDateString('en-US',{weekday:'long'})}.</b> Unlimited supply is assumed, but the provider needs at least 12 hours notice.</span></>:delta===0?<><Target/><span><b>All required trucks ordered.</b> No buffer for additional loads.</span></>:<><Truck/><span><b>{delta} extra trucks ordered.</b> Capacity buffer for this night.</span></>}</div></div><div className="cards">{bs.length?bs.map(b=>{const a=dayAssignments.find(a=>a.blockId===b.id)!;return <BlockCard key={b.id} block={b} day={d} days={days} tonsPerLoad={tonsPerLoad} scheduledLoads={a.scheduledLoads} appointment={a.appointment} confirmed={a.confirmed} move={move}/>}):<div className="empty"><CalendarDays/>Drop a ready block here to schedule</div>}</div></div>})}</section>
  <section className="season-status"><div><span>Season status · from the Bible</span><b>{livePlannerMeta.portfolio.acres_picked.toFixed(1)} acres picked</b></div><div><span>Harvest remaining</span><b>{livePlannerMeta.portfolio.acres_remaining.toFixed(1)} acres</b></div><div><span>Expected loads remaining</span><b>{livePlannerMeta.portfolio.required_trucks_one_trip} loads</b></div><small>Spreadsheet snapshot {short(livePlannerMeta.snapshotDate)}</small></section>
  </>}</div></main>{toast&&<div className="toast">{toast}</div>}
 </div>
}
