import { useState } from 'react'
import type { CSSProperties } from 'react'
import { CalendarDays, ChevronDown, CloudSun, Crosshair, Grape, Layers3, LayoutDashboard, MapPin, Menu, Plus, Search, Settings, Sparkles, Sprout, TrendingDown, Truck } from 'lucide-react'
import { GeoJSON, MapContainer, TileLayer } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import fieldDataRaw from '../../data/climate_operation_field_boundaries.geojson?raw'
import './styles.css'
import './requirements.css'

type View='Portfolio'|'Satellite'|'NDVI'|'Change'
const scenes=[
 {date:'Jun 08',full:'June 8, 2026',ndvi:.56,cloud:2.1,delta:3,low:19,normal:58,high:23},
 {date:'Jun 28',full:'June 28, 2026',ndvi:.62,cloud:1.4,delta:7,low:16,normal:61,high:23},
 {date:'Jul 18',full:'July 18, 2026',ndvi:.69,cloud:3.2,delta:9,low:13,normal:60,high:27},
 {date:'Aug 07',full:'August 7, 2026',ndvi:.71,cloud:.8,delta:4,low:12,normal:62,high:26},
 {date:'Aug 19',full:'August 19, 2026',ndvi:.68,cloud:3,delta:-8,low:14,normal:61,high:25},
]
const samples=[
 {key:'A',name:'Low vigor',place:'Southwest',ndvi:.51,brix:23.4,x:28,y:70,color:'#f3bd42'},
 {key:'B',name:'Representative',place:'Center',ndvi:.67,brix:22.8,x:52,y:48,color:'#b6d84f'},
 {key:'C',name:'High vigor',place:'Northeast',ndvi:.76,brix:22.4,x:72,y:29,color:'#43dc91'},
]
const sceneId='S2C_MSIL2A_20260811T184921_R113_T10SFH_20260812T000210'
const ndviTiles=`https://planetarycomputer.microsoft.com/api/data/v1/item/tiles/WebMercatorQuad/{z}/{x}/{y}@1x?collection=sentinel-2-l2a&item=${sceneId}&assets=B04&assets=B08&expression=%28B08-B04%29%2F%28B08%2BB04%29&rescale=0.2%2C0.9&colormap_name=rdylgn`
type FieldFeature={type:'Feature';id?:string;properties:{field_id:string;legacy_id:number;name:string;farm_name:string;area_value:number;area_unit:string;centroid:[number,number]};geometry:GeoJSON.Geometry}
type FieldCollection={type:'FeatureCollection';features:FieldFeature[]}
const allFields=JSON.parse(fieldDataRaw) as FieldCollection
const selectedId='d6c720e1-ec32-4592-a9bc-1847dacbcbcf'
const selectedField=allFields.features.find(f=>f.properties.field_id===selectedId) ?? allFields.features[0]
const [selectedLon,selectedLat]=selectedField.properties.centroid
const cluster={type:'FeatureCollection',features:allFields.features.filter(f=>f.properties.farm_name==='Lodi').sort((a,b)=>{const da=(a.properties.centroid[0]-selectedLon)**2+(a.properties.centroid[1]-selectedLat)**2;const db=(b.properties.centroid[0]-selectedLon)**2+(b.properties.centroid[1]-selectedLat)**2;return da-db}).slice(0,17)} as FieldCollection

export default function App(){
 const [view,setView]=useState<View>('Portfolio'),[sceneIndex,setSceneIndex]=useState(4),[draw,setDraw]=useState(false),[selected,setSelected]=useState('A'),[mobile,setMobile]=useState(false),[toast,setToast]=useState('')
 const scene=scenes[sceneIndex], notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2000)}
 const line=scenes.map((s,i)=>`${i?'L':'M'} ${i*112} ${128-(s.ndvi-.5)*270}`).join(' ')
 return <div className="vf-shell"><aside className={mobile?'open':''}><div className="brand"><span><Sprout/></span><div><b>VineFlow</b><small>HARVEST OPERATIONS</small></div></div><nav><button onClick={()=>{window.location.hash='overview'}}><LayoutDashboard/>Overview</button><button onClick={()=>{window.location.hash='blocks'}}><Grape/>Block Status</button><button onClick={()=>{window.location.hash='planner'}}><CalendarDays/>Harvest Planner</button><button onClick={()=>{window.location.hash='forecasting'}}><CloudSun/>Forecasting</button><button onClick={()=>{window.location.hash='planner'}}><Truck/>Fleet &amp; Logistics</button><button className="active"><Layers3/>Satellite Intelligence</button></nav><div className="aside-foot"><button><Settings/>Settings</button><div className="profile"><span>JM</span><div><b>Jordan Miller</b><small>Operations Manager</small></div></div></div></aside>
 <main><header><button className="hamb" onClick={()=>setMobile(!mobile)}><Menu/></button><div className="global-search"><Search/><input placeholder="Search vineyards, blocks, varieties…"/></div><div className="season"><span/> SENTINEL-2 LIVE <ChevronDown/></div></header><div className="content">
  <section className="topline"><div><p>SATELLITE INTELLIGENCE <span>•</span> LODI FARM</p><h1>FieldView Portfolio <em>/</em> {selectedField.properties.name}</h1><div className="block-meta"><b>Exact FieldView boundary</b><span>{(selectedField.properties.area_value*2.47105).toFixed(1)} acres</span><span>Field ID <code>{selectedField.properties.legacy_id}</code></span></div></div><button className="new-block" onClick={()=>setDraw(!draw)}><Plus/> {draw?'Finish boundary':'Draw new block'}</button></section>
  <div className="address"><Search/><input defaultValue="1525 East Jahant Rd, Acampo, CA 95220"/><button onClick={()=>notify('Map centered on East Jahant vineyard')}>Locate <Crosshair/></button></div>
  <section className="decision-strip"><article><span>EXPECTED TONS</span><b>244.5 <small>tons</small></b><p>B1 + B3 + B4 crop estimates</p></article><article><span>CURRENT SUGAR</span><b>23.6° <small>Brix</small></b><p>Syrah B2 · sampled Aug 19</p></article><article className="attention"><span>CANOPY PRIORITY</span><b>Scout weak zones first</b><p>Targeted sampling—not a harvest decision</p></article><article className="gap"><span>DATA GAP</span><b>1 missing estimate</b><p>LF Exotics B2 expected tons</p></article></section>
  <section className="workspace"><div className="map-card"><div className="map-toolbar"><div>{(['Portfolio','Satellite','NDVI','Change'] as View[]).map(v=><button className={view===v?'active':''} onClick={()=>setView(v)} key={v}>{v}</button>)}</div><span><Layers3/> {view==='Portfolio'?'Customer FieldView boundaries':'Sentinel-2 L2A · 10m'}</span></div>
   <div className={'map '+view.toLowerCase()+(draw?' drawing':'')} onClick={()=>draw&&notify('Boundary vertex added')}><MapContainer center={[selectedLat,selectedLon]} zoom={14} zoomControl attributionControl><TileLayer attribution="Esri World Imagery" url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"/>{view==='NDVI'&&<TileLayer className="native-ndvi" opacity={.86} attribution="Sentinel-2 L2A · Microsoft Planetary Computer" url={ndviTiles}/>}<GeoJSON data={cluster as GeoJSON.FeatureCollection} style={feature=>feature?.properties?.field_id===selectedId?{color:'#69f0a7',weight:3,fillColor:'#1c6d49',fillOpacity:.16}:{color:'#fff',weight:1.5,dashArray:'5 5',fillColor:'#d9e9df',fillOpacity:.05}}/></MapContainer>{view==='Portfolio'&&<div className="portfolio-map"><img src="/fieldview-portfolio.png" alt="Customer-supplied Climate FieldView portfolio map"/><div className="portfolio-caption"><span>108 supplied field boundaries</span><b>1,947 hectares · 3 farms</b><small>Lodi · Clements · Delta</small></div><button onClick={e=>{e.stopPropagation();setView('NDVI')}}><Sparkles/> Open Clements starting cluster</button></div>}
    {samples.map(s=><button key={s.key} className={'sample '+(selected===s.key?'selected':'')} style={{left:s.x+'%',top:s.y+'%','--pin':s.color} as CSSProperties} onClick={e=>{e.stopPropagation();setSelected(s.key)}}><i><b>{s.key}</b></i><span><b>Sample {s.key} · {s.name}</b>NDVI {s.ndvi.toFixed(2)} · {s.brix}° Brix</span></button>)}<div className="map-label"><b>{selectedField.properties.name.toUpperCase()}</b><small>EXACT FIELDVIEW GEOMETRY</small></div><div className="compass">N<br/>↑</div><div className="legend"><b>{view==='Change'?'CHANGE VIEW · DEMO ONLY':'NATIVE NDVI · B04 + B08'}</b><div className={view==='Change'?'changebar':'colorbar'}/><p><span>{view==='Change'?'Decline':'0.20'}</span><span>{view==='Change'?'Stable':'10 m source pixels'}</span><span>{view==='Change'?'Increase':'0.90'}</span></p></div>{draw&&<div className="draw-tip"><Sparkles/> Click along block edges to draw</div>}</div>
   <div className="map-footer"><div><span className="pulse"/><b>Sentinel-2 L2A</b><span>Aug 11, 2026</span></div><div><b>B04 + B08</b><span>native 10 m</span></div><div><b>0.075%</b><span>scene cloud cover</span></div><span title={sceneId}>MGRS 10SFH · auditable scene</span></div></div>
   <aside className="intel"><div className="intel-head"><div><p>BLOCK INTELLIGENCE · DEMO ANALYTICS</p><h2>Canopy variability</h2></div><span className="moderate">ILLUSTRATIVE</span></div><div className="big-stat"><span>Average NDVI · pending calculation</span><b>{scene.ndvi.toFixed(2)}</b><small><TrendingDown/> Illustrative comparison—not yet computed</small></div><div className="distribution"><div><p><i className="low"/>Low vigor <b>{scene.low}%</b></p><p><i className="normal"/>Normal <b>{scene.normal}%</b></p><p><i className="high"/>High vigor <b>{scene.high}%</b></p></div><span><i style={{width:scene.low+'%'}}/><i style={{width:scene.normal+'%'}}/><i style={{width:scene.high+'%'}}/></span></div>
    <div className="samples-title"><div><p>SUGGESTED FIELD SAMPLES</p><span>Representative zones across canopy vigor</span></div><b>3 POINTS</b></div><div className="sample-list">{samples.map(s=><button className={selected===s.key?'active':''} key={s.key} onClick={()=>setSelected(s.key)}><i style={{background:s.color}}>{s.key}</i><div><b>{s.name}</b><span><MapPin/> {s.place} · NDVI {s.ndvi}</span></div><strong>{s.brix}°<small>Brix</small></strong></button>)}</div><button className="route" onClick={()=>notify('Sample route exported to field crew')}><MapPin/> Send sample route to field crew</button><p className="caution"><Sparkles/> Customer hypothesis: weaker canopy may ripen earlier. Prioritize Brix sampling here; NDVI alone does not determine ripeness, yield, or harvest order.</p></aside>
  </section><section className="timeline-card"><div className="timeline-head"><div><p>2026 CANOPY TIMELINE</p><h2>Vegetation index through the season</h2></div><div><span><i/>2026 season</span><span><i/>5-year average</span></div></div><div className="chart"><div className="axis"><span>0.80</span><span>0.70</span><span>0.60</span><span>0.50</span></div><svg viewBox="0 0 448 145" preserveAspectRatio="none"><path className="average" d="M 0 112 C 80 87 145 65 224 58 S 345 52 448 59"/><path className="area" d={line+' L 448 140 L 0 140 Z'}/><path className="line" d={line}/>{scenes.map((s,i)=><circle className={i===sceneIndex?'active':''} key={s.date} cx={i*112} cy={128-(s.ndvi-.5)*270} r={i===sceneIndex?6:4}/>)}</svg></div><div className="dates">{scenes.map((s,i)=><button className={i===sceneIndex?'active':''} onClick={()=>setSceneIndex(i)} key={s.date}><b>{s.date}</b><span>{s.ndvi.toFixed(2)} NDVI</span></button>)}</div></section>
 </div></main>{toast&&<div className="toast">✓ {toast}</div>}</div>
}
